# -*- mode: ruby -*-
# vi: set ft=ruby :

require('../provisioning/vagrant-provision-reboot-plugin.rb')

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision :shell, :inline => "echo \"Europe/London\" | sudo tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata"
  config.vm.provision :shell, path: "../provisioning/base-bootstrap.sh"
  config.vm.provision :shell, path: "../provisioning/install-unity-1.sh"
  config.vm.provision :shell, path: "../provisioning/install-rabbitmq.sh"
  config.vm.provision :unix_reboot
  
   config.vm.provider "virtualbox" do |vb|
     # Don't boot with headless mode
     vb.gui = true
  
     vb.customize ["modifyvm", :id, "--memory", "1024"]
   end
  
   config.vm.network "forwarded_port", guest: 5672, host: 5672
   config.vm.network "forwarded_port", guest: 15672, host: 15672
end
