# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision :shell, :inline => "echo \"Europe/London\" | sudo tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata"
  config.vm.provision :shell, path: "../../provisioning/base-bootstrap.sh"
  config.vm.provision :shell, path: "../../provisioning/install-go.sh"
  config.vm.provision :shell, path: "../../provisioning/install-nodejs.sh"
  config.vm.provision :shell, path: "../../provisioning/install-ruby.sh"
  config.vm.provision :shell, path: "../../provisioning/install-java.sh"
  config.vm.provision :shell, path: "../../provisioning/install-logstash.sh"
  config.vm.provision :shell, path: "../../provisioning/install-nginx.sh"
  config.vm.provision :shell, path: "../../provisioning/install-git.sh"

   config.vm.provider "virtualbox" do |vb|
     vb.gui = true

     vb.customize ["modifyvm", :id, "--memory", "512"]
   end

  config.vm.synced_folder "C:/vagrant/share","/home/vagrant/share"

end
