# -*- mode: ruby -*-
# vi: set ft=ruby :

require('../../provisioning/vagrant-provision-reboot-plugin.rb')

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision :shell, :inline => "echo \"Europe/London\" | sudo tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata"
  config.vm.provision :shell, path: "../../provisioning/base-bootstrap.sh"
  config.vm.provision :shell, path: "../../provisioning/install-unity.sh"
  config.vm.provision :shell, path: "../../provisioning/install-nodejs.sh"
  config.vm.provision :shell, path: "../../provisioning/install-ruby.sh"
  config.vm.provision :shell, path: "../../provisioning/install-dashing.sh"
  config.vm.provision :unix_reboot

  config.vm.network "forwarded_port", guest: 3030, host: 3333

   config.vm.provider "virtualbox" do |vb|
     vb.gui = true

     vb.customize ["modifyvm", :id, "--memory", "1024"]
   end

  config.vm.synced_folder "C:/Users/danfox/src/git/booking-process-dashboard","/home/vagrant/booking-process-dashboard"

end
