# -*- mode: ruby -*-
# vi: set ft=ruby :

require('../../provisioning/vagrant-provision-reboot-plugin.rb')

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  #config.vm.network "private_network", ip: "192.168.64.20"

  config.vm.network "forwarded_port", guest: 27017, host: 27017
  config.vm.network "forwarded_port", guest: 28017, host: 28017

  config.vm.define :config do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.provision :shell, :inline => "echo \"Europe/London\" | sudo tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata"
    config.vm.provision :shell, path: "../../provisioning/base-bootstrap.sh"
    config.vm.provision :shell, path: "../../provisioning/install-mongodb.sh"
    config.vm.provision :shell, :inline => "sed -i -e 's/bind_ip = 127.0.0.1/#bind_ip = 127.0.0.1/' /etc/mongod.conf"
    config.vm.provision :shell, :inline => "sed -i -e 's/#httpinterface = true/httpinterface = true/' /etc/mongod.conf"
    config.vm.provision :shell, :inline => "sed -i -e 's/#auth = true/auth = true/' /etc/mongod.conf"
    config.vm.provision :unix_reboot

    config.vm.provider "virtualbox" do |vm|
  #    vm.name = "mongodb"
  #vm.gui = true
    end

    config.vm.hostname = "mongodb"
  end

end
