# -*- mode: ruby -*-
# vi: set ft=ruby :

require('../../provisioning/vagrant-provision-reboot-plugin.rb')

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

#  config.vm.define :ansible do |ansible|
#    ansible.vm.box = "ubuntu/trusty64"
#    ansible.vm.network "private_network", ip: "192.168.64.21"
#    ansible.vm.provision :shell, :inline => "echo \"Europe/London\" | sudo tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata"
#    ansible.vm.provision :shell, path: "../../provisioning/base-bootstrap.sh"
#    ansible.vm.provision :shell, path: "../../provisioning/install-ansible.sh"
#
#    ansible.vm.provision :unix_reboot
#    ansible.vm.hostname = "ansible"
#    ansible.vm.provider "virtualbox" do |vm|
#      #vm.gui = true
#    end
#  end

  config.vm.define :teamcity do |teamcity|
    teamcity.vm.box = "ubuntu/trusty64"
    teamcity.vm.network "private_network", ip: "192.168.64.22"
    teamcity.vm.provision :shell, :inline => "echo \"Europe/London\" | sudo tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata"
    teamcity.vm.provision :shell, path: "../../provisioning/base-bootstrap.sh"
    teamcity.vm.provision :shell, path: "../../provisioning/install-java.sh"
    teamcity.vm.provision :shell, path: "../../provisioning/install-teamcity.sh"

    teamcity.vm.provision :shell, path: "config-teamcity.sh"

    teamcity.vm.provision :unix_reboot
    teamcity.vm.hostname = "teamcity"
    teamcity.vm.provider "virtualbox" do |vm|
      #vm.gui = true
      vm.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
end
